### ISSUE TITLE
Data sources

### ISSUE THREAD

**Issue by Christosc96** [stanford-futuredata/abae#1]
Is it possible to share a source for the data used in the work? I am mainly referring  to the amazon datasets since, for example, the office reviews do not correspond to the current version of the dataset (1,243,186 data points in the current version vs 800,144 in the paper experiments). Thanks in advance!

**Comment by ddkang** [comment]
We excluded reviews that didn't have posters as described in the manuscript

**Comment by Christosc96** [comment]
Thanks for your answer, although for the office supplies reviews that I was referring to, there are no posters, unless I am missing something.

**Comment by ddkang** [comment]
https://nijianmo.github.io/amazon/index.html#complete-data

Office Products | 5-core (800,357 reviews)

**Comment by Christosc96** [comment]
In your paper and the available data files there are 800144 data points instead of 800357. What I am looking for, is a way to match the two dataset indexes so that a model trained on the dataset can be compared to your predicate outputs.
